[package]
name = "vn-ui-definitions"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { workspace = true }
web-time = { workspace = true }
vn-scene = { path = "../vn-scene" }
vn-ui-animation = { path = "../vn-ui-animation" }
vn-ui-animation-macros = { path = "../vn-ui-animation-macros" }
# ide marks it as unused, but it is very much used by rand
getrandom = { workspace = true, features = ["wasm_js"] }
rand = { workspace = true }

[features]
debug_outlines = []