[package]
name = "vn-tile-map-editor-web"
version = "0.2.1"
authors = ["Voided Name"]
categories = ["wasm"]
edition = "2024"

[features]
debug_outlines = ["vn-tile-map-editor-logic/debug_outlines"]
example_map = ["vn-tile-map-editor-logic/example_map"]

[lib]
crate-type = ["cdylib"]

[dependencies]
vn-tile-map-editor-logic = { path = "../vn-tile-map-editor-logic" }
vn-wgpu-window = { path = "../../vn-wgpu-window" }
vn-scene = { path = "../../vn-scene" }
wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
log = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }
anyhow = { workspace = true }
rfd = { workspace = true }