[package]
name = "vn-farming-logic"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
debug_outlines = ["vn-ui-definitions/debug_outlines"]

[dependencies]
vn-tilemap = { path = "../../vn-tilemap" }
vn-scene = { path = "../../vn-scene" }
vn-wgpu-window = { path = "../../vn-wgpu-window" }
vn-ui = { path = "../../vn-ui" }
vn-ui-definitions = { path = "../../vn-ui-definitions" }
log = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
web-time = { workspace = true }
winit = { workspace = true }
serde_json = { workspace = true }
tar = { workspace = true }
