[package]
name = "vn-tile-map-editor-native"
version = "0.2.0"
edition = "2024"


[features]
debug_outlines = ["vn-tile-map-editor-logic/debug_outlines"]
example_map = ["vn-tile-map-editor-logic/example_map"]

[dependencies]
vn-tile-map-editor-logic = { path = "../vn-tile-map-editor-logic" }
anyhow = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
rfd = { workspace = true, features = [] }
pollster = { workspace = true }