[package]
name = "vn-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
vn-scene = { path = "../vn-scene" }
vn-ui-animation = { path = "../vn-ui-animation" }
vn-ui-animation-macros = { path = "../vn-ui-animation-macros" }
vn-ui-macros = { path = "../vn-ui-macros" }
vn-ui-definitions = { path = "../vn-ui-definitions" }
vn-utils = { path = "../vn-utils" }
winit = { workspace = true }
web-time = { workspace = true }
log = { workspace = true }